Stop storing thread HTML in Bundles (Crashlytics #606)
There's an error being thrown for some people:
Fatal Exception: java.lang.RuntimeException
android.os.TransactionTooLargeException: data parcel size 1439824 bytes

According to Dianne Hackborn (comments here: http://blog.sqisland.com/2016/09/transactiontoolargeexception-crashes-nougat.html)
each process has at best a 1MB buffer for this data, and we're probably exceeding that by storing a whole page's HTML.
 I've taken that out and made the fragment restore itself by rebuilding the page from the cached data in the database instead.

 Also changed some logging to try and make it more informative, and removed a conditional in #syncThread that's always true
(the final value passed in is always the one passed back out) - shouldn't need checking anyway since we're cancelling existing requests